//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fchat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public int iddiadiem { get; set; }
        public int MaLoai { get; set; }
        public string TenDD { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTaChiTiet { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> Gia { get; set; }
    }
}
