//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fchat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        public int IdKs { get; set; }
        public int idLoai { get; set; }
        public int Idtn { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> SoGiuong { get; set; }
    }
}
