//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fchat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongTien
    {
        public int Idpt { get; set; }
        public int Idloaipt { get; set; }
        public string TenPT { get; set; }
        public string BienSo { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public Nullable<decimal> Gia { get; set; }
    }
}
