//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fchat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int IdTin { get; set; }
        public string ThongTin { get; set; }
        public string Image { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string NguoiDang { get; set; }
    }
}
