//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fchat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IDuser { get; set; }
        public string HoTen { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Phai { get; set; }
    }
}
